# Generated by Django 3.2.5 on 2021-12-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xunjian', '0002_auto_20211222_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xunjian',
            name='time',
        ),
    ]
